package com.nexio.tv.core.catalog.rails

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Generates `app/build/reports/catalog-rail-uniformity-audit/catalog-rail-uniformity.md` and
 * enforces strict conformance: every file in the manifest must implement [CatalogRailSource],
 * and every `CatalogRailSource` implementation under `app/src/main/java/com/nexio/tv/` must be
 * declared in the manifest.
 *
 * Wrapped by the Gradle task `generateCatalogRailUniformityAudit` (registered in
 * `app/build.gradle.kts`).
 *
 * Plan 8 of the catalog-rails uniformity series retired the `@CatalogRailNotYetUniform`
 * tracking annotation; this test no longer recognises a TRACKED state. Adding a new rail
 * source requires both a new file under `data/catalog/rails/` AND a new manifest entry —
 * the audit fails on either side missing.
 */
class CatalogRailUniformityAuditTest {

    private enum class Verdict { CONFORMANT, MISSING }

    private data class Row(val path: String, val verdict: Verdict)

    @Test
    fun `every known rail loader is conformant and no unauthorized impls exist`() {
        val projectRoot = locateProjectRoot()
        val manifest = projectRoot.resolve("app/src/test/resources/catalog/known_rail_loader_paths.txt")
        require(manifest.exists()) {
            "Manifest missing: ${manifest.absolutePath}"
        }
        val manifestPaths = manifest.readLines()
            .map { it.trim() }
            .filter { it.isNotEmpty() }

        val rows = manifestPaths.map { rel -> classify(projectRoot.resolve(rel), rel) }

        // 1. Strict guard: any file in src/main/java implementing CatalogRailSource MUST be in the manifest.
        val mainSrc = projectRoot.resolve("app/src/main/java/com/nexio/tv")
        val implFiles = mainSrc.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .filter { f ->
                val text = f.readText()
                CONFORMANT_PATTERNS.any { it.containsMatchIn(text) }
            }
            .map { it.relativeTo(projectRoot).path }
            .toSet()
        val unauthorized = implFiles - manifestPaths.toSet()
        assertTrue(
            "Files implement CatalogRailSource but are not in known_rail_loader_paths.txt:\n" +
                unauthorized.joinToString("\n") +
                "\n\nIf you are adding a new rail provider: also add the file path to the manifest.\n" +
                "If you are removing one: remove the path from the manifest.",
            unauthorized.isEmpty()
        )

        // 2. Write the markdown report (always — even on success).
        val reportDir = projectRoot.resolve("app/build/reports/catalog-rail-uniformity-audit")
        reportDir.mkdirs()
        val report = reportDir.resolve("catalog-rail-uniformity.md")
        report.writeText(renderReport(rows))

        // 3. Conformance assertion.
        val missing = rows.filter { it.verdict == Verdict.MISSING }
        assertEquals(
            "Files in manifest do not implement CatalogRailSource:\n" +
                missing.joinToString("\n") { it.path },
            emptyList<Row>(),
            missing
        )
    }

    private fun classify(file: File, relPath: String): Row {
        if (!file.exists()) {
            return Row(relPath, Verdict.MISSING)
        }
        val text = file.readText()
        val isConformant = CONFORMANT_PATTERNS.any { it.containsMatchIn(text) }
        return Row(relPath, if (isConformant) Verdict.CONFORMANT else Verdict.MISSING)
    }

    private fun renderReport(rows: List<Row>): String = buildString {
        appendLine("# Catalog Rail Uniformity Audit")
        appendLine()
        appendLine("Generated by `CatalogRailUniformityAuditTest`. Do not hand-edit.")
        appendLine()
        appendLine("Strict mode (Plan 8): every manifest entry must implement `CatalogRailSource`,")
        appendLine("and every `CatalogRailSource` implementation in production code must be in the manifest.")
        appendLine()
        appendLine("| File | Verdict |")
        appendLine("|------|---------|")
        rows.forEach { r -> appendLine("| ${r.path} | ${r.verdict.name} |") }
        appendLine()
        val conformant = rows.count { it.verdict == Verdict.CONFORMANT }
        val missing = rows.count { it.verdict == Verdict.MISSING }
        appendLine("**Summary:** $conformant conformant, $missing missing.")
    }

    private fun locateProjectRoot(): File {
        // user.dir is mandatory at JVM startup. Walk up looking for the marker.
        val cwd = File(System.getProperty("user.dir") ?: ".").canonicalFile
        var candidate: File? = cwd
        while (candidate != null) {
            if (candidate.resolve("app/build.gradle.kts").exists() ||
                candidate.resolve("settings.gradle.kts").exists()
            ) {
                return candidate
            }
            candidate = candidate.parentFile
        }
        return cwd
    }

    private companion object {
        /**
         * Matches `class <Name> ... : ... CatalogRailSource ... {` (the supertype clause
         * up to the body's opening brace). Allows multi-line spans because Kotlin class
         * declarations with multi-arg constructors typically place the `: SuperType` clause
         * on a separate line from the `class` keyword.
         *
         * The match is bounded by the first `{` (the class body opening), so
         * `CatalogRailSource` mentions inside method bodies, KDoc, or string literals
         * AFTER the first `{` cannot false-positive.
         */
        private val CONFORMANT_PATTERNS = listOf(
            Regex("""(?:^|\n)\s*(?:abstract\s+|open\s+|sealed\s+|data\s+|internal\s+|private\s+)*class\s+\w+[^{]*?[,:]\s*[^{]*?\bCatalogRailSource\b[^{]*?\{""", RegexOption.DOT_MATCHES_ALL),
            Regex("""(?:^|\n)\s*(?:internal\s+|private\s+)*object\s+\w+[^{]*?[,:]\s*[^{]*?\bCatalogRailSource\b[^{]*?\{""", RegexOption.DOT_MATCHES_ALL)
        )
    }
}
