package com.nexio.tv.core.catalog.rails

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Generates `app/build/reports/catalog-rail-uniformity-audit/catalog-rail-uniformity.md` and
 * verifies every known rail-loader file is either conformant (implements [CatalogRailSource])
 * or tracked (carries [CatalogRailNotYetUniform]).
 *
 * Wrapped by the Gradle task `generateCatalogRailUniformityAudit` (registered in
 * `app/build.gradle.kts`).
 */
class CatalogRailUniformityAuditTest {

    private enum class Verdict { CONFORMANT, TRACKED, MISSING }

    private data class Row(
        val path: String,
        val verdict: Verdict,
        val reason: String?,
        val tracking: String?
    )

    @Test
    fun `every known rail loader is conformant or tracked`() {
        val projectRoot = locateProjectRoot()
        val manifest = projectRoot.resolve("app/src/test/resources/catalog/known_rail_loader_paths.txt")
        require(manifest.exists()) {
            "Manifest missing: ${manifest.absolutePath}"
        }
        val manifestPaths = manifest.readLines()
            .map { it.trim() }
            .filter { it.isNotEmpty() }

        val rows = manifestPaths.map { rel -> classify(projectRoot.resolve(rel), rel) }

        // 1. Drift guard: any file in src/main/java carrying the annotation MUST be in the manifest.
        val mainSrc = projectRoot.resolve("app/src/main/java/com/nexio/tv")
        val annotatedFiles = mainSrc.walkTopDown()
            .filter { it.isFile && it.extension == "kt" }
            .filter { it.readText().contains("@CatalogRailNotYetUniform") }
            .map { it.relativeTo(projectRoot).path }
            .toSet()
        val undeclared = annotatedFiles - manifestPaths.toSet()
        assertTrue(
            "Files carry @CatalogRailNotYetUniform but are not in known_rail_loader_paths.txt:\n" +
                undeclared.joinToString("\n"),
            undeclared.isEmpty()
        )

        // 2. Write the markdown report (always — even on success).
        val reportDir = projectRoot.resolve("app/build/reports/catalog-rail-uniformity-audit")
        reportDir.mkdirs()
        val report = reportDir.resolve("catalog-rail-uniformity.md")
        report.writeText(renderReport(rows))

        // 3. Conformance assertion.
        val missing = rows.filter { it.verdict == Verdict.MISSING }
        assertEquals(
            "Files in manifest with neither CatalogRailSource impl nor @CatalogRailNotYetUniform:\n" +
                missing.joinToString("\n") { it.path },
            emptyList<Row>(),
            missing
        )
    }

    private fun classify(file: File, relPath: String): Row {
        if (!file.exists()) {
            return Row(relPath, Verdict.MISSING, reason = "file not found", tracking = null)
        }
        val text = file.readText()
        val isConformant = CONFORMANT_PATTERNS.any { it.containsMatchIn(text) }
        if (isConformant) return Row(relPath, Verdict.CONFORMANT, reason = null, tracking = null)
        val annotationMatch = ANNOTATION_PATTERN.find(text)
        if (annotationMatch != null) {
            val reason = REASON_PATTERN.find(annotationMatch.value)?.groupValues?.get(1)
            val tracking = TRACKING_PATTERN.find(annotationMatch.value)?.groupValues?.get(1)
            return Row(relPath, Verdict.TRACKED, reason = reason, tracking = tracking)
        }
        return Row(relPath, Verdict.MISSING, reason = null, tracking = null)
    }

    private fun renderReport(rows: List<Row>): String = buildString {
        appendLine("# Catalog Rail Uniformity Audit")
        appendLine()
        appendLine("Generated by `CatalogRailUniformityAuditTest`. Do not hand-edit.")
        appendLine()
        appendLine("| File | Verdict | Reason | Tracking |")
        appendLine("|------|---------|--------|----------|")
        rows.forEach { r ->
            appendLine(
                "| ${r.path} | ${r.verdict.name} | ${r.reason ?: ""} | ${r.tracking ?: ""} |"
            )
        }
        appendLine()
        val conformant = rows.count { it.verdict == Verdict.CONFORMANT }
        val tracked = rows.count { it.verdict == Verdict.TRACKED }
        val missing = rows.count { it.verdict == Verdict.MISSING }
        appendLine("**Summary:** $conformant conformant, $tracked tracked, $missing missing.")
    }

    private fun locateProjectRoot(): File {
        // user.dir is mandatory at JVM startup. Walk up looking for the marker.
        val cwd = File(System.getProperty("user.dir") ?: ".").canonicalFile
        var candidate: File? = cwd
        while (candidate != null) {
            if (candidate.resolve("app/build.gradle.kts").exists() ||
                candidate.resolve("settings.gradle.kts").exists()
            ) {
                return candidate
            }
            candidate = candidate.parentFile
        }
        return cwd
    }

    private companion object {
        private val CONFORMANT_PATTERNS = listOf(
            Regex("""class\s+\w+[^{]*:\s*[^{]*\bCatalogRailSource\b"""),
            Regex("""object\s+\w+[^{]*:\s*[^{]*\bCatalogRailSource\b""")
        )
        private val ANNOTATION_PATTERN = Regex(
            """@CatalogRailNotYetUniform\s*\(([^)]*)\)""", RegexOption.DOT_MATCHES_ALL
        )
        private val REASON_PATTERN = Regex("""reason\s*=\s*"([^"]*)"""")
        private val TRACKING_PATTERN = Regex("""tracking\s*=\s*"([^"]*)"""")
    }
}
