// automatically generated by the FlatBuffers compiler, do not modify

package hyperhdrnet;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Clear extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Clear getRootAsClear(ByteBuffer _bb) { return getRootAsClear(_bb, new Clear()); }
  public static Clear getRootAsClear(ByteBuffer _bb, Clear obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Clear __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int priority() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createClear(FlatBufferBuilder builder,
      int priority) {
    builder.startTable(1);
    Clear.addPriority(builder, priority);
    return Clear.endClear(builder);
  }

  public static void startClear(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addPriority(FlatBufferBuilder builder, int priority) { builder.addInt(0, priority, 0); }
  public static int endClear(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Clear get(int j) { return get(new Clear(), j); }
    public Clear get(Clear obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

