// automatically generated by the FlatBuffers compiler, do not modify

package hyperhdrnet;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class P010Image extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static P010Image getRootAsP010Image(ByteBuffer _bb) { return getRootAsP010Image(_bb, new P010Image()); }
  public static P010Image getRootAsP010Image(ByteBuffer _bb, P010Image obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public P010Image __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int dataY(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int dataYLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector dataYVector() { return dataYVector(new ByteVector()); }
  public ByteVector dataYVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer dataYAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer dataYInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int dataUv(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int dataUvLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector dataUvVector() { return dataUvVector(new ByteVector()); }
  public ByteVector dataUvVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer dataUvAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer dataUvInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int width() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int height() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int strideY() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int strideUv() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createP010Image(FlatBufferBuilder builder,
      int dataYOffset,
      int dataUvOffset,
      int width,
      int height,
      int strideY,
      int strideUv) {
    builder.startTable(6);
    P010Image.addStrideUv(builder, strideUv);
    P010Image.addStrideY(builder, strideY);
    P010Image.addHeight(builder, height);
    P010Image.addWidth(builder, width);
    P010Image.addDataUv(builder, dataUvOffset);
    P010Image.addDataY(builder, dataYOffset);
    return P010Image.endP010Image(builder);
  }

  public static void startP010Image(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addDataY(FlatBufferBuilder builder, int dataYOffset) { builder.addOffset(0, dataYOffset, 0); }
  public static int createDataYVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createDataYVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startDataYVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addDataUv(FlatBufferBuilder builder, int dataUvOffset) { builder.addOffset(1, dataUvOffset, 0); }
  public static int createDataUvVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createDataUvVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startDataUvVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addWidth(FlatBufferBuilder builder, int width) { builder.addInt(2, width, 0); }
  public static void addHeight(FlatBufferBuilder builder, int height) { builder.addInt(3, height, 0); }
  public static void addStrideY(FlatBufferBuilder builder, int strideY) { builder.addInt(4, strideY, 0); }
  public static void addStrideUv(FlatBufferBuilder builder, int strideUv) { builder.addInt(5, strideUv, 0); }
  public static int endP010Image(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public P010Image get(int j) { return get(new P010Image(), j); }
    public P010Image get(P010Image obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

