package com.nexio.tv.core.integration

enum class IntegrationProvider {
    ADDON,
    TRAKT,
    SIMKL,
    TMDB,
    TVDB,
    KITSU,
    MDBLIST,
    OMDB,
    CUSTOM_IMDB,
    THEINTRODB,
    ANISKIP,
    ANIMESKIP,
    ARM,
    RPDB,
    TOP_POSTERS,
    FANART_TV,
    REAL_DEBRID,
    PREMIUMIZE,
    TORBOX,
    EASY_DEBRID,
    SHADOW_COLLECTOR,
    GITHUB,
    YOUTUBE_TRAILER,
    OPEN_SUBTITLES,
    SUBTITLE_SOURCE_DOWNLOAD,
    SUBTITLE_TRANSLATION,
    WYZIE_SUBTITLES
}
