package com.nexio.tv.core.anime.projection

enum class FallbackReason {
    NO_TVDB_MAPPING,
    NO_TMDB_MAPPING,
    LOW_CONFIDENCE_FLAT_KITSU,
    OVERLAY_MISSING,
    KITSU_NOT_IN_PACK,
    NO_CURATED_SEASON,
    SEASON_MARKER_HENTAI,
    SEASON_MARKER_UNKNOWN,
    EPISODE_OUT_OF_RANGE,
    OVERLAY_DROPPED,
}
