FORMAT: 1A
HOST: https://api.ratingposterdb.com/

# RPDB API

The [Rating Poster Database](https://ratingposterdb.com/) (RPDB) is an API that allows fetching movie and series posters with ratings based on IMDB / TMDB / TVDB IDs.

Additional features include: backdrops with ratings, logos with ratings, adding badges to posters ([130+ badge options](#reference/0/badges)), adding custom text labels to posters, custom poster images and much more!

Examples of images that are made available through the RPDB API can be seen on the [Examples Page](https://ratingposterdb.com/examples).


## API Keys

In order to use the RPDB API you must first subscribe to one of the Tiers [on Patreon](https://patreon.com/rpdb).

Upon subscribing the API Key will be received by e-mail.


## API URL

The API should always be accessed over SSL.
```
https://api.ratingposterdb.com
```

## Request Limits

Each Tier has a monthly request limit, upon passing the request limit the service will respond with an error.

Caching of images is allowed for personal use and recommended for larger projects.

| Tier | Request Limit |
|---|---|
| 1 | 50,000 |
| 2 | 100,000 |
| 3 | 150,000 |
| 4 | 750,000 |


## Detecting API Key Tier

The tier of each API Key can be derived from the API Key itself from the first 2 characters.

| Tier | API Key Starts With |
|---|---|
| 1 | t1-... |
| 2 | t2-... |
| 3 | t3-... |
| 4 | t4-... |


## Supported IDs

RPDB supports the following Metadata IDs:
- IMDB (example: `tt0944947`)
- TMDB (needs to be prefixed by `movie-` or `series-`, example: `series-225171`)
- TVDB (needs to be prefixed by `movie-` or `series-`, example: `movie-190`)


## Stremio Addons

Implementing RPDB with Stremio addons is easy, the image URL should be changed to the following:
- poster: `https://api.ratingposterdb.com/{userApiKey}/{mediaType}/poster-default/{mediaId}.jpg`
- logo: `https://api.ratingposterdb.com/{userApiKey}/{mediaType}/logo-default/{mediaId}.png`
- backdrop: `https://api.ratingposterdb.com/{userApiKey}/{mediaType}/backdrop-default/{mediaId}.jpg`

Where the values are:
- `userApiKey`: the user's RPDB API Key
- `mediaType`: can be either `imdb`, `tmdb` or `tvdb`
- `mediaId`: the Metadata ID (from IMDB, TMDB or TVDB) as explained in the "Supported IDs" section

**Note:** We highly recommend using `?fallback=true` for images in Stremio addons, this will make the posters fallback to a normal poster (without ratings) if an item is currently missing ratings.

There is nothing else required to implement RPDB in Stremio addons except changing the image URL as explained above. Users can then change all aspects of their RPDB images by visiting https://manager.ratingposterdb.com/ separately and all RPDB images will reflect their chosen settings.

## Validating API Keys [/{apiKey}/isValid]

If the API Key is valid it will return a `200` status code along with a JSON body.

If it is invalid, it will return a `403` status code along with a text response.

+ Parameters
    + apiKey (required, string) ... The user's API Key

### Example [GET]

+ Response 200 (application/json)

        {
            "valid": true
        }


+ Response 403 (text/plain)

        API Key is Invalid

## Checking API Key Request Count [/{apiKey}/requests]

This action responds with the current request count and Tier request limit.

+ Parameters
    + apiKey (required, string) ... The user's API Key

### Example [GET]

+ Response 200 (application/json)

        {
            "req": 1502,
            "limit": 20000
        }


## Posters with Ratings [/{apiKey}/{idType}/{posterType}/{mediaId}.jpg]

Tier 0 only supports `poster-default`, all other tiers support all 4 poster types.

Poster types starting with `textless-` will prefer the textless versions of the posters (if available).

Examples:

- [poster-default](https://ratingposterdb.com/static/tier-1.jpg)
- [textless-default](https://ratingposterdb.com/static/tier-1-textless.jpg)
- [poster-certs](https://ratingposterdb.com/static/tier-2-1.jpg)
- [poster-mc](https://ratingposterdb.com/static/tier-2-2.jpg)
- [poster-rt](https://ratingposterdb.com/static/tier-2-3.jpg)

Note: For anime, this endpoint will also reply with MAL rating, for details check the "Anime Ratings" category of this page.

Note 2: Adding `?fallback=true` to the querystring will make the API return a normal poster in case ratings are missing, otherwise the API will reply with an error in such a case.

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)

### Example [GET]

+ Response 200 (image/jpeg)

## Localized Posters with Ratings [/{apiKey}/{idType}/{posterType}/{mediaId}.jpg{?lang}]

**Only supported with Tier 1+**

You can use the `?lang=` query parameter with any ISO 639-1 code to prefer posters in a particular language.

In addition to ISO 639-1 two letter language code, the following language codes are also supported to cover regional language variation:
- "pt-PT" - Portuguese (Portugal)
- "pt-BR" - Portuguese (Brazil)
- "es-ES" - Spanish (Spain)
- "es-MX" - Spanish (Mexico)
- "zh-CN" - Chinese (Mainland China)
- "zh-HK" - Chinese (Hong Kong)
- "zh-SG" - Chinese (Singapore)
- "zh-TW" - Chinese (Taiwan)

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + lang (required, string, `en`) ... Poster language in ISO 639-1 (2 letter language code)

### Example [GET]

+ Response 200 (image/jpeg)

## Themes [/{apiKey}/{idType}/{posterType}/{mediaId}.jpg{?theme}]

You can set the theme of a poster by setting the `?theme=` option.

Available themes:
- "bar": dark rating bar (bottom) [Tier 0+]
- "blocks": dark blocks (bottom) [Tier 0+]
- "rounded-blocks": dark rounded blocks (bottom) [Tier 0+]
- "boxes": dark boxes (bottom) [Tier 0+]
- "sharp-blocks": dark sharp blocks (bottom) [Tier 1+]
- "stripes-right": dark stripes skewed to the right (bottom) [Tier 1+]
- "stripes-left": dark stripes skewed to the left (bottom) [Tier 1+]
- "light-bar": light rating bar (bottom) [Tier 1+]
- "light-blocks": light blocks (bottom) [Tier 1+]
- "light-rounded-blocks": light rounded blocks (bottom) [Tier 1+]
- "light-boxes": light boxes (bottom) [Tier 1+]
- "light-sharp-blocks": light sharp blocks (bottom) [Tier 1+]
- "light-stripes-right": light stripes skewed to the right (bottom) [Tier 1+]
- "light-stripes-left": light stripes skewed to the left (bottom) [Tier 1+]

Themes can be edited with `?ratingBarPos` to change the rating bar position, `?fontScale` to change the font size and any of the other styling options.

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + theme (required, string, `default`) ... Poster theme name

### Example [GET]

+ Response 200 (image/jpeg)

## Labels [/{apiKey}/{idType}/{posterType}/{mediaId}.jpg{?label}]

**Only supported with Tier 2+**

To add a label with custom text to a poster, you can add `?label=` followed by the URL encoded label text.

[See Poster Example](https://ratingposterdb.com/static/tier-3-label.jpg)

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + label (required, string, `custom text`) ... Custom text to set as poster label

### Example [GET]

+ Response 200 (image/jpeg)

## Badges [/{apiKey}/{idType}/{posterType}/{mediaId}.jpg{?badges}]

**Only supported with Tier 2+**

To add a badges to a poster, you can add `?badges=` followed by a list of badge tags.

Badge tags should be separated by `,`.

A poster can have a maximum of 4 badges at one time, if more badges are set only the first 4 will show.

In addition to the badge tags below, you can also use 2 letter country codes prefixed by `country.` to show country flags as badges. Example: `?badges=country.de` (to show the flag of Germany)

Dynamic badges:

| Tag | Type | Title | Subtitle | Color |  
|---|---|---|---|---|
| commonsense | age rating | known age rating | Common Sense | Silver |
| commonsensegold | age rating | known age rating | Common Sense | Gold |
| age_rating | age rating | known age rating | Common Sense | Silver |
| age_rating_gold | age rating | known age rating | Common Sense | Gold |
| us_age_rating | age rating | US age rating | Common Sense | Silver |
| us_age_rating_gold | age rating | US age rating | Common Sense | Gold |
| auto_resolution | video quality | highest known video resolution | Varied | Bronze/Silver/Gold |
| auto_dv_hdr | color range | highest known release | Varied | Gold/Multicolor |
| auto_lang | flag by spoken language | country flag | none | none |
| auto_lang_no_en | flag by spoken language (ignores EN) | country flag | none | none |
| auto_country | flag by production country | country flag | none | none |
| auto_country_no_us | flag by production country (ignores US) | country flag | none | none |

Supported badge tags:

| Tag | Type | Title | Subtitle | Color |  
|---|---|---|---|---|
| 4k | video quality | 4K | Ultra HD | Gold |
| 4kupscaled | video quality | 4K | Upscaled | Silver |
| 1080p | video quality | 1080p | Full HD | Gold |
| 720p | video quality | 720p | HD | Silver |
| 720pgold | video quality | 720p | HD | Gold |
| 2k | video quality | 2K | Quad HD | Gold |
| 5k | video quality | 5K | Ultra HD | Gold |
| 8k | video quality | 8K | Ultra HD | Gold |
| 576p | video quality | 576p | SD | Bronze |
| 480p | video quality | 480p | SD | Bronze |
| 360p | video quality | 360p | SD | Bronze |
| 240p | video quality | 240p | SD | Bronze |
| hd | video quality | HD | Medium Quality | Silver |
| sd | video quality | SD | Low Quality | Bronze |
| 3d | video type | 3D | Stereoscopic | Gold |
| hdrcolor | color range | HDR | True Color | Multicolor |
| hdr | color range | HDR | True Color | Silver |
| hdr10plus | color range | HDR10+ | True Color | Silver |
| hdr10plus_colorful | color range | HDR10+ | Multicolor | Silver |
| dolbyvision | color range | (icon) | Dolby Vision | Multicolor |
| dolbyvisioncolor | color range | (icon) | Dolby Vision [alt 1] | Multicolor |
| dolbyvisioncoloralt | color range | (icon) | Dolby Vision [alt 2] | Multicolor |
| dv_hdr_gold | color range | DV/HDR | True Color | Gold |
| dv_hdr_colorful | color range | DV/HDR | True Color | Multicolor |
| hybrid_gold | color range | HYBRID | True Color | Gold |
| hybrid_colorful | color range | HYBRID | True Color | Multicolor |
| imaxgold | aspect ratio | IMAX | Widescreen | Gold |
| imax | aspect ratio | IMAX | Widescreen | Silver |
| remuxgold | video source | REMUX | Lossless | Gold |
| remux | video source | REMUX | Lossless | Silver |
| bluray | video source | BluRay | Format | Silver |
| dvd | video source | DVD | Format | Silver |
| web | video source | WEB | Format | Silver |
| mkv | video container | MKV | Matroska | Silver |
| mp4 | video container | MP4 | MPEG-4 | Silver |
| avi | video container | AVI | A/V Interleave | Silver |
| h264 | video encoding | h264 | AVC | Silver |
| h265 | video encoding | h265 | HEVC | Silver |
| h266 | video encoding | h266 | VVC | Silver |
| audio20 | audio | 2.0 | Stereo | Silver |
| audio51 | audio | 5.1 | Surround | Silver |
| audio71 | audio | 7.1 | Surround | Silver |
| dd20 | audio | DD2.0 | Stereo | Silver |
| dd51 | audio | DD5.1 | Surround | Silver |
| ddp20 | audio | DDP2.0 | Stereo | Silver |
| ddp51 | audio | DDP5.1 | Surround | Silver |
| ddp71 | audio | DDP7.1 | Surround | Silver |
| truehd51lossless | audio | TrueHD5.1 | Lossless | Silver |
| truehd51surround | audio | TrueHD5.1 | Surround | Silver |
| truehd71lossless | audio | TrueHD7.1 | Lossless | Silver |
| truehd71surround | audio | TrueHD7.1 | Surround | Silver |
| pcm51lossless | audio | PCM5.1 | Lossless | Silver |
| pcm51surround | audio | PCM5.1 | Surround | Silver |
| pcm71lossless | audio | PCM7.1 | Lossless | Silver |
| pcm71surround | audio | PCM7.1 | Surround | Silver |
| atmos3dsound | audio | Atmos | 3D Sound | Silver |
| atmossurround | audio | Atmos | Surround | Silver |
| 5stars | personal rating | 5 ✯ | Perfect | Gold |
| 4stars | personal rating | 4 ✯ | Great | Silver |
| 3stars | personal rating | 3 ✯ | Good | Silver |
| 2stars | personal rating | 2 ✯ | Bad | Bronze |
| 1stars | personal rating | 1 ✯ | Horrible | Bronze |
| cannesnominee | awards | NOMINEE | CANNES | Silver |
| canneswinner | awards | WINNER | CANNES | Gold |
| criterion | awards | (icon) | CRITERION | Gold |
| emmynominee | awards | NOMINEE | EMMYS | Silver |
| emmywinner | awards | WINNER | EMMYS | Gold |
| goldenglobesnominee | awards | NOMINEE | GOLDEN GLOBES | Silver |
| goldenglobeswinner | awards | WINNER | GOLDEN GLOBES | Gold |
| mastersofthecinema | awards | (icon) | CLASSICS | Gold |
| oscarsnominee | awards | NOMINEE | OSCARS | Silver |
| oscarswinner | awards | WINNER | OSCARS | Gold |
| sundancenominee | awards | NOMINEE | SUNDANCE | Silver |
| sundancewinner | awards | WINNER | SUNDANCE | Gold |
| sundancewinner | awards | WINNER | SUNDANCE | Gold |
| directorscut | special edition | DIRECTOR'S CUT | SPECIAL EDITION | Gold |
| extendedcut | special edition | EXTENDED CUT | SPECIAL EDITION | Gold |
| g | age rating | G | CERTIFICATION | Silver |
| g_gold | age rating | G | CERTIFICATION | Gold |
| nc_17 | age rating | NC-17 | CERTIFICATION | Silver |
| nc_17_gold | age rating | NC-17 | CERTIFICATION | Gold |
| nr | age rating | NR | CERTIFICATION | Silver |
| nr_gold | age rating | NR | CERTIFICATION | Gold |
| pg_13 | age rating | PG-13 | CERTIFICATION | Silver |
| pg_13_gold | age rating | PG-13 | CERTIFICATION | Gold |
| pg | age rating | PG | CERTIFICATION | Silver |
| pg_gold | age rating | PG | CERTIFICATION | Gold |
| r | age rating | R | CERTIFICATION | Silver |
| r_gold | age rating | R | CERTIFICATION | Gold |
| tv_14 | age rating | TV-14 | CERTIFICATION | Silver |
| tv_14_gold | age rating | TV-14 | CERTIFICATION | Gold |
| tv_g | age rating | TV-G | CERTIFICATION | Silver |
| tv_g_gold | age rating | TV-G | CERTIFICATION | Gold |
| tv_ma | age rating | TV-MA | CERTIFICATION | Silver |
| tv_ma_gold | age rating | TV-MA | CERTIFICATION | Gold |
| tv_pg | age rating | TV-PG | CERTIFICATION | Silver |
| tv_pg_gold | age rating | TV-PG | CERTIFICATION | Gold |
| tv_y | age rating | TV-Y | CERTIFICATION | Silver |
| tv_y_gold | age rating | TV-Y | CERTIFICATION | Gold |
| tv_y7 | age rating | TV-Y7 | CERTIFICATION | Silver |
| tv_y7_gold | age rating | TV-Y7 | CERTIFICATION | Gold |
| age(2..18) | age rating | age (2..18)+ | COMMON SENSE | Silver |
| age(2..18)gold | age rating | age (2..18)+ | COMMON SENSE | Gold |


[See Poster Example](https://ratingposterdb.com/static/tier-3-badge-left.jpg)

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `id-type`
    + badges (required, string, `4k`) ... Badge tags separated by , (comma)

### Example [GET]

+ Response 200 (image/jpeg)


## Maximum Number of Badges [/{apiKey}/{idType}/{posterType}/{mediaId}.jpg{?badges,maxBadges}]

**Only supported with Tier 3+**

The maximum number of badges to show at once on an image, the default value for this differs based on rating bar position and image type.

The value is expected to be a number, example: `1`, `2`, `3`, `4`, etc

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + badges (required, string, `4k`) ... Badge tags separated by , (comma)
    + maxBadges (required, string, `2`) ... Maximum badges, can be: `1`, `2`, `3`, `4`, etc

### Example [GET]

+ Response 200 (image/jpeg)


## Badge Position [/{apiKey}/{idType}/{posterType}/{mediaId}.jpg{?badges,badgePos}]

**Only supported with Tier 3+**

The badge position can be set with the `?badgePos=` query parameter and works for both posters and backdrops.

Supported badge positions: `left` (default), `center`, `right`, `bottom|left`, `bottom|center`, `bottom|right`

[Example for Left Badges](https://ratingposterdb.com/static/tier-3-badge-left.jpg)

[Example for Center Badges](https://ratingposterdb.com/static/tier-3-badge-center.jpg)

[Example for Right Badges](https://ratingposterdb.com/static/tier-3-badge-right.jpg)

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + badges (required, string, `4k`) ... Badge tags separated by , (comma)
    + badgePos (required, string, `center`) ... Badge position, can be: `left` (default), `center`, `right`

### Example [GET]

+ Response 200 (image/jpeg)


## TMDB Poster Choices [/{apiKey}/{idType}/{posterType}/tmdb-poster/{mediaId}/{tmdbPosterFilename}]

**Only supported with Tier 2+**

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + tmdbPosterFilename (required, string, `kqjL17yufvn9OVLyXYpvtyrFfak.jpg`) ... The image filename from the [TMDB Poster Image Response](https://developers.themoviedb.org/3/getting-started/images)

### Example [GET]

+ Response 200 (image/jpeg)


## Custom Poster Images [/{apiKey}/{idType}/{posterType}/custom-poster/{mediaId}.jpg{?img}]

**Only supported with Tier 3+**

The `?img=` query parameter needs to be set to an image URI (URL encoded).

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + img (required, string, `https://image.tmdb.org/t/p/w780/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg`) ... Any image URI to use as poster

### Example [GET]

+ Response 200 (image/jpeg)


## Backdrops with Ratings [/{apiKey}/{idType}/{backdropType}/{mediaId}.jpg]

**Only supported with Tier 2+**

[Example of Backdrop](https://ratingposterdb.com/static/tier-2-backdrop.jpg)

Note: as with posters, backdrops also support custom ratings choice, rating order, as well as all Tier 3 customisation such as choosing where the ratings are shown and the color of the rating background and text color.

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + backdropType (required, string, `backdrop-default`) ... The backdrop type, currently only `backdrop-default` is supported
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)

### Example [GET]

+ Response 200 (image/jpeg)


## Logos with Ratings [/{apiKey}/{idType}/{logoType}/{mediaId}.png]

**Only supported with Tier 2+**

Note: compared to posters and backdrops which are JPG, it is important to note that logos are PNG images as they require transparency.

Note 2: due to limited space in the logo image, logos do not support badges

Note 3: as with posters, logos also support custom ratings choice, rating order, as well as all Tier 3 customisation such as choosing where the ratings are shown and the color of the rating background and text color.

[Example of Logo](https://ratingposterdb.com/static/tier-2-logo.png)

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + logoType (required, string, `logo-default`) ... The logo type, currently only `logo-default` is supported
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)

### Example [GET]

+ Response 200 (image/png)


## Anime Ratings [/{apikey}/{idType}/{posterType}/{mediaId}.jpg]

All known anime movies and series include MAL rating by default (except for the free tier), so the API is the same as in the "Posters with Ratings" category of this page.

In the case of anime, instead of receiving IMDB + RT + MC ratings, you will receive MAL + IMDB + RT (+ MC if any other rating is missing) with the following poster types: `poster-default`, `poster-certs`, `poster-rt`, `poster-mc`, `backdrop-default`, `textless-default`, `textless-certs`, `textless-rt`, `textless-mc`.

This applies for all Tiers.

+ Parameters
    + apikey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + posterType (required, string, `poster-default`) ... The poster rating type, can be: `poster-default`, `poster-certs`, `poster-mc`, `poster-rt`, `textless-default`, `textless-certs`, `textless-mc`, `textless-rt`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)

### Example [GET]

+ Response 200 (image/jpeg)


## More Ratings [/{apiKey}/{idType}/{imageType}/{mediaId}.jpg{?order}]

**Only supported with Tier 1+**

The `?order=` query parameter needs to be set to a text that includes one or more rating tags, split by comma. This querystring parameter works with `rating-order` image type for posters, `backdrop-default` image type for backdrops and `logo-default` image type for logos.

Example order query parameter values:
- `myanimelist,imdb,commonsense,letterboxd`
- `imdb,tmdb,trakt`

Currently available rating tags:
- `imdb` : IMDB audience rating
- `tmdb` : TMDB audience rating
- `trakt` : Trakt audience rating
- `tomatoes-critics` : Rotten Tomaotes critics rating
- `tomatoes-audience` : Rotten Tomaotes audience rating
- `metacritic-critics` : Metacritic critics rating
- `metacritic-audience` : Metacritic audience rating
- `letterboxd` : Letterboxd audience rating
- `rogerebert` : Roger Ebert rating
- `myanimelist` : MyAnimeList audience rating
- `commonsense` : Common Sense Media age rating
- `mdblist` : MDBList rating
- `us-age` : US age rating
- `overall-rating` : overall rating (based on all audience and critics scores)
- `critics-rating` : overall critics rating (based on all critics scores)
- `audience-rating` : overall audience rating (based on all audience scores)

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + imageType (required, string, `rating-order`) ... For posters use `rating-order`, for backdrops use `backdrop-default`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + order (required, string, `myanimelist,imdb,commonsense,letterboxd`) ... Text including one or more rating tags

### Example [GET]

+ Response 200 (image/jpeg)


## Image Size [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?imageSize}]

**Only supported with Tier 2+**

Poster image sizes:
- `medium`: 580x859 (default)
- `large`: 1280x1896 (Tier 2+)
- `verylarge`: 2000x2962 (Tier 3+)

Backdrop image sizes:
- `medium`: 1920x1080 (default)
- `small`: 1280x720 (Tier 2+)
- `large`: 3840x2160 (Tier 3+)

Logo image sizes:
- `medium`: 780x244 (default)
- `large`: 1722x539 (Tier 2+)
- `verylarge`: 2689x841 (Tier 3+)

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + imageSize (required, string, `large`) ... Text including preferred image size

### Example [GET]

+ Response 200 (image/jpeg)


## Font Size [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?fontScale}]

**Only supported with Tier 2+**

Supported values:
- `1` (default)
- `1.1`
- `1.2`
- `1.3`
- `1.4`
- `1.5`

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + fontScale (required, string, `1`) ... Font size

### Example [GET]

+ Response 200 (image/jpeg)


## Font Weight [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?fontWeight}]

**Only supported with Tier 2+**

Supported values:
- `0` - Normal (default)
- `1` - Bold

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + fontWeight (required, string, `1`) ... Font weight

### Example [GET]

+ Response 200 (image/jpeg)


## Font Style [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?textStyle}]

**Only supported with Tier 2+**

Supported values:
- `0` : Default, will show ratings in the form of: 7.4/10, 75%, 2/5, etc
- `1` : Normalizes ratings to all be between 1-100 and removes "/5", "/10", "%" suffix, examples: 75, 12, 39
- `2` : Only remove "/5" and "/10" suffix, examples: 7.4, 75%, 2.2, etc

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + textStyle (required, string, `1`) ... Font Style, can be: `0`, `1`, `2`

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Position [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarPos}]

**Only supported with Tier 3+**

Poster image rating bar positions:
- `bottom` (default)
- `top`
- `left-top`
- `left-center`
- `left-bottom`
- `right-top`
- `right-center`
- `right-bottom`

Backdrop image rating bar positions:
- `right-top` (default)
- `right-center`
- `right-bottom`
- `left-top`
- `left-center`
- `left-bottom`

Logo image rating bar positions:
- `bottom` (default)
- `top`
- `left-top`
- `left-center`
- `left-bottom`
- `right-top`
- `right-center`
- `right-bottom`
- `bottom-left`
- `bottom-right`
- `top-left`
- `top-right`

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarPos (required, string, `top`) ... Text including preferred rating bar position

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Opacity [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarOpacity}]

**Only supported with Tier 3+**

Rating bar opacity is set with a float value (ex: `0.5`, `0.2`).

While `0.0` or `0` are not supported, using `0.01` will make the rating bar completely transparent.

While `1.0` or `1` are not supported, using `0.99` will make the rating bar remove transparency.

Both posters and backdrops support `?ratingBarOpacity=`

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarOpacity (required, string, `0.5`) ... Text including preferred rating bar opacity

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Background Color [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarColor}]

**Only supported with Tier 3+**

The rating bar background color is set with a text value for the HTML color name (ex: `red`, `blue`) or the hex value of the color (ex: `#FFE4C4`).

Both posters and backdrops support `?ratingBarColor=`

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarColor (required, string, `blue`) ... Text including preferred rating bar color

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Type [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarType}]

**Only supported with Tier 3+**

The rating bar type can be either "bar" (default) or "blocks". The "blocks" type supports exclusive settings such as "ratingBarRoundness" and "ratingBarPadding".

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarType (required, string, `blocks`) ... Rating bar type (either `bar` or `blocks`)

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Roundness [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarRoundness}]

**Only supported with Tier 3+**

The rating bar roundness applies only for "blocks" ratingBarType or supported themes (that include "blocks" or "stripes" in the name), it can be set to "default" (minimal rounded corners), "full" (completely rounded corners) or any number (pixels) including "0" (sharp corners).

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarRoundness (required, string, `full`) ... Rating block corner roundness for supported themes

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Padding [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarPadding}]

**Only supported with Tier 3+**

The rating block padding applies only for "blocks" ratingBarType or supported themes (that include "blocks" or "stripes" in the name), it can be set to any number (pixels) including "0".

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarPadding (required, string, `15`) ... Rating block padding for supported themes

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Margin [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarMargin}]

**Only supported with Tier 3+**

The rating block margin applies only for "blocks" ratingBarType or supported themes (that include "blocks" or "stripes" in the name), it can be set to any number (pixels) including "0".

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarMargin (required, string, `15`) ... Rating block padding for supported themes

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Stroke Width [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarStrokeWidth}]

**Only supported with Tier 3+**

The rating bar stroke width applies only for "blocks" ratingBarType or supported themes (that include "blocks" or "stripes" in the name), it can be set to "default" (minimal stroke width) or any number (pixels) including "0" (no width).

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarStrokeWidth (required, string, `full`) ... Rating block corner roundness for supported themes

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Stroke Color [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarStrokeColor}]

**Only supported with Tier 3+**

The rating bar stroke side applies only for "blocks" ratingBarType or supported themes (that include "blocks" or "stripes" in the name), it can be set to "default" (all sides) or one of the following: "right", "left", "top", "bottom"

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarStrokeColor (required, string, `red`) ... Stroke color

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Stroke Side [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?strokeSide}]

**Only supported with Tier 3+**

The rating bar stroke side applies only for "blocks" ratingBarType or supported themes (that include "blocks" or "stripes" in the name), it can be set to "default" (all sides) or one of the following: "right", "left", "top", "bottom"

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + strokeSide (required, string, `right`) ... Stroke side

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Skew Direction [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?ratingBarSkewDirection}]

**Only supported with Tier 3+**

The rating block skew direction, applies only for "blocks" ratingBarType or supported themes (that include "blocks"), it can be set to: "left" or "right".

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + ratingBarSkewDirection (required, string, `left`) ... Color of the rating block border

### Example [GET]

+ Response 200 (image/jpeg)


## Rating Bar Font Color [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?fontColor}]

**Only supported with Tier 3+**

The rating bar font color is set with a text value for the HTML color name (ex: `red`, `blue`) or the hex value of the color (ex: `#FFE4C4`).

Both posters and backdrops support `?fontColor=`

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + fontColor (required, string, `blue`) ... Text including preferred rating bar font color

### Example [GET]

+ Response 200 (image/jpeg)


## Logo Styles [/{apiKey}/{idType}/poster-certs/{mediaId}.jpg{?logoStyle}]

**Only supported with Tier 3+**

Setting this value to "1" will make the rating logos round, setting this value to "2" will disable the logos.

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + logoStyle (required, string, `1`) ... If rating logo should be a round image or disabled

### Example [GET]

+ Response 200 (image/jpeg)


## Backdrop Certificates Position [/{apiKey}/{idType}/backdrop-default/{mediaId}.jpg{?certsPos}]

**Only supported with Tier 3+**

The certificates (such as "certified fresh" or "must watch") from the backdrops can be moved with the `certsPos` query parameter.

Only backdrops support `?certsPos=`.

Available positions for backdrop certificates:
- `left` (default)
- `right`

+ Parameters
    + apiKey (required, string) ... The user's API Key
    + idType (required, string, `imdb`) ... The requesting id type, can be: `imdb`, `tmdb`, `tvdb`
    + mediaId (required, string, `tt2395427`) ... The ID for the movie / series, depending on the chosen `idType`, when using the `tmdb` or `tvdb` id types you should also include the media type in the ID (TMDB/TVDB ID examples: `movie-155` or `series-155`)
    + certsPos (required, string, `right`) ... Text including preferred backdrop certificate position

### Example [GET]

+ Response 200 (image/jpeg)
